apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-nginx
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/denismironiuk/test-nginx.git
    path: .
    targetRevision: main
    directory:
      recurse: true
      exclude: '{issuer/**,cert-manager/**,ingress-nginx/**}'

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
